services:
  api_campus:
    build: .
    ports:
      - "8080:8080"
    environment:
      environment:
        - DATABASE_URL=jdbc:postgresql://db_api:5432/test
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=admin
    restart: always
    depends_on:
      - db_api

  db_api:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-q", "-U", "postgres" ]
      timeout: 10s
      retries: 10
